
server:
  port: 8081
spring:
  profiles:
    active: dev


#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/vhr?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: root
#    type: com.alibaba.druid.pool.DruidDataSource
#  rabbitmq:
#    username: guest
#    password: guest
#    host: 47.97.221.113
#    port: 5672
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
#  level:



